/*
===============================================================================
안전하길 DB FINAL
01_schema.sql
===============================================================================
[기능]
- FINAL v8 기준 public Core 22개 테이블 생성
- PK / FK / UNIQUE / CHECK / DEFAULT 정의
- Supabase Auth의 auth.users는 생성하지 않고 FK로만 참조
- PostGIS geometry 컬럼 9개 생성

[전제]
- 00_extensions.sql 실행 완료
- Supabase Auth가 이미 존재하는 Supabase 프로젝트
- 신규 구축용 baseline SQL: 운영 DB에서 반복 실행하지 않음

[Core 22]
users, user_term_agreements, driving_preferences, favorite_places,
recent_searches, routing_policies, route_requests, route_candidates,
route_candidate_links, admins, admin_audit_logs, datasets, data_update_logs,
service_areas, road_nodes, road_links, road_turns, road_link_features,
road_risk_scores, traffic_accidents, notices, inquiries
===============================================================================
*/

BEGIN;

SET LOCAL search_path = public, extensions, gis;

-- ============================================================================
-- 1. 회원 / 사용자 설정
-- ============================================================================

CREATE TABLE public.users (
    id uuid PRIMARY KEY
        REFERENCES auth.users(id) ON DELETE CASCADE,
    username varchar(20),
    email varchar(255) NOT NULL,
    nickname varchar(10) NOT NULL,
    signup_provider varchar(20) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    onboarding boolean NOT NULL DEFAULT false,
    withdrawn_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_users_username
        CHECK (username IS NULL OR username ~ '^[a-z][a-z0-9_]{4,19}$'),
    CONSTRAINT ck_users_email_lowercase
        CHECK (email = lower(email)),
    CONSTRAINT ck_users_nickname
        CHECK (nickname ~ '^[가-힣A-Za-z0-9]{2,10}$'),
    CONSTRAINT ck_users_signup_provider
        CHECK (signup_provider IN ('local','naver','kakao','google')),
    CONSTRAINT ck_users_withdrawal_state
        CHECK (is_active = true OR withdrawn_at IS NOT NULL)
);

COMMENT ON TABLE public.users IS
'서비스 회원 프로필. 시스템 식별자는 Supabase auth.users.id이며 email은 속성이다.';

CREATE TABLE public.user_term_agreements (
    user_id uuid PRIMARY KEY
        REFERENCES public.users(id) ON DELETE CASCADE,
    agreed_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.user_term_agreements IS
'필수 서비스/개인정보/위치 약관 3종 전체 동의 완료 기록. 본문/버전은 DB에 저장하지 않는다.';

CREATE TABLE public.driving_preferences (
    user_id uuid PRIMARY KEY
        REFERENCES public.users(id) ON DELETE CASCADE,
    intersection_score smallint NOT NULL,
    pedestrian_zone_score smallint NOT NULL,
    narrow_road_score smallint NOT NULL,
    turn_conflict_score smallint NOT NULL,
    structure_score smallint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_driving_preferences_intersection
        CHECK (intersection_score BETWEEN 1 AND 5),
    CONSTRAINT ck_driving_preferences_pedestrian
        CHECK (pedestrian_zone_score BETWEEN 1 AND 5),
    CONSTRAINT ck_driving_preferences_narrow
        CHECK (narrow_road_score BETWEEN 1 AND 5),
    CONSTRAINT ck_driving_preferences_turn
        CHECK (turn_conflict_score BETWEEN 1 AND 5),
    CONSTRAINT ck_driving_preferences_structure
        CHECK (structure_score BETWEEN 1 AND 5)
);

COMMENT ON TABLE public.driving_preferences IS
'온보딩/마이페이지의 5개 운전 부담 설문 원점수(1~5). 라우팅 가중치는 routing_policies에서 관리한다.';

CREATE TABLE public.favorite_places (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL
        REFERENCES public.users(id) ON DELETE CASCADE,
    place_type varchar(20) NOT NULL,
    place_name varchar(200) NOT NULL,
    custom_name varchar(100),
    address text,
    road_address text,
    geom geometry(Point,4326) NOT NULL,
    provider varchar(20) NOT NULL DEFAULT 'kakao',
    provider_place_id varchar(100),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_favorite_places_type
        CHECK (place_type IN ('home','work','custom')),
    CONSTRAINT ck_favorite_places_provider
        CHECK (provider IN ('kakao'))
);

COMMENT ON TABLE public.favorite_places IS
'사용자 저장 장소. home/work는 사용자별 각 1개, 전체 최대 5개는 Backend에서 검증한다.';

CREATE TABLE public.recent_searches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL
        REFERENCES public.users(id) ON DELETE CASCADE,
    place_name varchar(200) NOT NULL,
    address text,
    road_address text,
    geom geometry(Point,4326) NOT NULL,
    provider varchar(20) NOT NULL DEFAULT 'kakao',
    provider_place_id varchar(100),
    searched_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_recent_searches_provider
        CHECK (provider IN ('kakao'))
);

COMMENT ON TABLE public.recent_searches IS
'검색어 타이핑 이력이 아니라 사용자가 실제 선택한 장소의 최근검색 기록. 사용자당 최근 10~20개 유지 권장.';

-- ============================================================================
-- 2. 관리자 / 운영 권한
-- ============================================================================

CREATE TABLE public.admins (
    id uuid PRIMARY KEY
        REFERENCES auth.users(id) ON DELETE CASCADE,
    email varchar(255) NOT NULL,
    role varchar(20) NOT NULL DEFAULT 'admin',
    is_active boolean NOT NULL DEFAULT true,
    granted_by_admin_id uuid
        REFERENCES public.admins(id) ON DELETE SET NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_admins_email_lowercase
        CHECK (email = lower(email)),
    CONSTRAINT ck_admins_role
        CHECK (role IN ('super_admin','admin'))
);

COMMENT ON TABLE public.admins IS
'Supabase Auth 관리자에 대한 서비스 권한 프로필. 비밀번호/세션은 저장하지 않는다.';

CREATE TABLE public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_admin_id uuid
        REFERENCES public.admins(id) ON DELETE SET NULL,
    target_admin_id uuid
        REFERENCES public.admins(id) ON DELETE SET NULL,
    action varchar(50) NOT NULL,
    before_data jsonb,
    after_data jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_admin_audit_logs_action
        CHECK (action IN (
            'create_admin',
            'change_role',
            'activate',
            'deactivate',
            'delete_admin'
        ))
);

COMMENT ON TABLE public.admin_audit_logs IS
'관리자 생성/역할/활성 변경 감사 이력. 민감정보와 IP는 MVP에서 저장하지 않는다.';

-- ============================================================================
-- 3. 데이터셋 / ETL 관리
-- ============================================================================

CREATE TABLE public.datasets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    source_name varchar(150) NOT NULL,
    description text,
    update_method varchar(20) NOT NULL DEFAULT 'batch',
    update_cycle varchar(50),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_datasets_update_method
        CHECK (update_method IN ('batch','api','manual'))
);

COMMENT ON TABLE public.datasets IS
'관리 대상 데이터셋 마스터. current_version/last_updated_at은 data_update_logs 최신 실행에서 파생한다.';

CREATE TABLE public.data_update_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    dataset_id bigint NOT NULL
        REFERENCES public.datasets(id) ON DELETE RESTRICT,
    status varchar(30) NOT NULL DEFAULT 'running',
    trigger_type varchar(20) NOT NULL DEFAULT 'manual',
    target_count integer NOT NULL DEFAULT 0,
    processed_count integer NOT NULL DEFAULT 0,
    success_count integer NOT NULL DEFAULT 0,
    failure_count integer NOT NULL DEFAULT 0,
    source_version varchar(100),
    error_summary text,
    executed_by uuid
        REFERENCES public.admins(id) ON DELETE SET NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,

    CONSTRAINT ck_data_update_logs_status
        CHECK (status IN ('running','completed','partial_failed','failed')),
    CONSTRAINT ck_data_update_logs_trigger_type
        CHECK (trigger_type IN ('initial','manual','scheduled')),
    CONSTRAINT ck_data_update_logs_target_count
        CHECK (target_count >= 0),
    CONSTRAINT ck_data_update_logs_processed_count
        CHECK (
            processed_count >= 0
            AND processed_count = success_count + failure_count
        ),
    CONSTRAINT ck_data_update_logs_success_count
        CHECK (success_count >= 0),
    CONSTRAINT ck_data_update_logs_failure_count
        CHECK (failure_count >= 0)
);

COMMENT ON TABLE public.data_update_logs IS
'데이터셋별 ETL/갱신 실행 이력. error_summary에는 민감정보를 저장하지 않는다.';

-- ============================================================================
-- 4. 서비스 영역 / 도로 네트워크
-- ============================================================================

CREATE TABLE public.service_areas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code varchar(20) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    geom geometry(MultiPolygon,4326) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    effective_from date,
    effective_to date,

    CONSTRAINT ck_service_areas_effective_period
        CHECK (
            effective_to IS NULL
            OR effective_from IS NULL
            OR effective_to >= effective_from
        )
);

COMMENT ON TABLE public.service_areas IS
'사용자 출발/도착 서비스 허용 영역. 도로망 구축용 강남구+1km buffer와 별개이다.';

CREATE TABLE public.road_nodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id varchar(50) NOT NULL UNIQUE,
    geom geometry(Point,4326) NOT NULL,
    node_type varchar(30),
    is_intersection boolean,
    source_updated_at timestamptz
);

COMMENT ON TABLE public.road_nodes IS
'표준노드링크 Node 그래프. 대용량 원본 payload는 별도 원천파일에서 관리한다.';

CREATE TABLE public.road_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id varchar(50) NOT NULL UNIQUE,
    from_node_id bigint NOT NULL
        REFERENCES public.road_nodes(id) ON DELETE RESTRICT,
    to_node_id bigint NOT NULL
        REFERENCES public.road_nodes(id) ON DELETE RESTRICT,
    geom geometry(LineString,4326) NOT NULL,
    road_name varchar(200),
    road_class varchar(30),
    lane_count smallint,
    length_m numeric(10,2) NOT NULL,
    base_time_sec numeric(10,2),
    speed_limit_kph smallint,
    one_way boolean NOT NULL DEFAULT false,
    source_updated_at timestamptz,

    CONSTRAINT ck_road_links_lane_count
        CHECK (lane_count IS NULL OR lane_count > 0),
    CONSTRAINT ck_road_links_length
        CHECK (length_m >= 0),
    CONSTRAINT ck_road_links_base_time
        CHECK (base_time_sec IS NULL OR base_time_sec >= 0),
    CONSTRAINT ck_road_links_speed_limit
        CHECK (speed_limit_kph IS NULL OR speed_limit_kph > 0)
);

COMMENT ON TABLE public.road_links IS
'표준노드링크 Link 그래프와 경로 계산용 기본 속성. route_candidate_links가 참조하므로 운영 후 무단 TRUNCATE 금지.';

CREATE TABLE public.road_turns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    via_node_id bigint NOT NULL
        REFERENCES public.road_nodes(id) ON DELETE CASCADE,
    from_road_link_id bigint NOT NULL
        REFERENCES public.road_links(id) ON DELETE CASCADE,
    to_road_link_id bigint NOT NULL
        REFERENCES public.road_links(id) ON DELETE CASCADE,
    turn_type varchar(30) NOT NULL,
    is_allowed boolean NOT NULL DEFAULT true,
    source_turn_code varchar(30),
    penalty_sec numeric(8,2) NOT NULL DEFAULT 0,
    source_updated_at timestamptz,

    CONSTRAINT uq_road_turns_transition
        UNIQUE (via_node_id, from_road_link_id, to_road_link_id),
    CONSTRAINT ck_road_turns_type
        CHECK (turn_type IN ('straight','left','right','uturn','other')),
    CONSTRAINT ck_road_turns_penalty
        CHECK (penalty_sec >= 0)
);

COMMENT ON TABLE public.road_turns IS
'링크→링크 회전 관계 및 제한. 실제 Backend 경로엔진에서 설치된 pgRouting 버전에 맞는 turn-aware 방식을 사용한다.';

CREATE TABLE public.road_link_features (
    road_link_id bigint PRIMARY KEY
        REFERENCES public.road_links(id) ON DELETE CASCADE,
    complex_intersection_score numeric(10,4) NOT NULL DEFAULT 0,
    pedestrian_zone_score numeric(10,4) NOT NULL DEFAULT 0,
    narrow_road_score numeric(10,4) NOT NULL DEFAULT 0,
    turn_conflict_score numeric(10,4) NOT NULL DEFAULT 0,
    structure_score numeric(10,4) NOT NULL DEFAULT 0,
    accident_score numeric(10,4) NOT NULL DEFAULT 0,
    feature_version varchar(50) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_road_link_features_intersection CHECK (complex_intersection_score >= 0),
    CONSTRAINT ck_road_link_features_pedestrian CHECK (pedestrian_zone_score >= 0),
    CONSTRAINT ck_road_link_features_narrow CHECK (narrow_road_score >= 0),
    CONSTRAINT ck_road_link_features_turn CHECK (turn_conflict_score >= 0),
    CONSTRAINT ck_road_link_features_structure CHECK (structure_score >= 0),
    CONSTRAINT ck_road_link_features_accident CHECK (accident_score >= 0)
);

COMMENT ON TABLE public.road_link_features IS
'설문 5요소 및 사고 특성에 대응하는 링크 전처리 Feature. DB에서는 0 이상만 보장하며 정규화는 모델/정책에서 수행한다.';

CREATE TABLE public.road_risk_scores (
    road_link_id bigint NOT NULL
        REFERENCES public.road_links(id) ON DELETE CASCADE,
    risk_version varchar(80) NOT NULL,
    time_bucket smallint NOT NULL DEFAULT -1,
    model_version varchar(50) NOT NULL,
    objective_risk_score numeric(12,6) NOT NULL,
    risk_cost numeric(12,6) NOT NULL,
    generated_by_update_log_id uuid
        REFERENCES public.data_update_logs(id) ON DELETE SET NULL,
    calculated_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (road_link_id, risk_version, time_bucket),

    CONSTRAINT ck_road_risk_scores_time_bucket
        CHECK (time_bucket BETWEEN -1 AND 23),
    CONSTRAINT ck_road_risk_scores_objective
        CHECK (objective_risk_score >= 0),
    CONSTRAINT ck_road_risk_scores_cost
        CHECK (risk_cost >= 0)
);

COMMENT ON TABLE public.road_risk_scores IS
'링크별 객관 위험 사전계산 결과. time_bucket=-1은 전일 공통, 0~23은 시간대별 결과이다.';

CREATE TABLE public.traffic_accidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taas_accident_id varchar(100) NOT NULL UNIQUE,
    occurred_at timestamptz,
    geom geometry(Point,4326) NOT NULL,
    accident_type varchar(100),
    severity varchar(50),
    accident_count integer NOT NULL DEFAULT 1,
    matched_road_link_id bigint
        REFERENCES public.road_links(id) ON DELETE SET NULL,
    match_confidence numeric(5,4),
    raw_payload jsonb,
    source_updated_at timestamptz,

    CONSTRAINT ck_traffic_accidents_count
        CHECK (accident_count >= 1),
    CONSTRAINT ck_traffic_accidents_confidence
        CHECK (match_confidence IS NULL OR match_confidence BETWEEN 0 AND 1)
);

COMMENT ON TABLE public.traffic_accidents IS
'TAAS 사고 데이터 및 도로링크 매칭 결과. raw_payload에는 개인정보를 제거한 필요한 원천 필드만 저장한다.';

-- ============================================================================
-- 5. 라우팅 정책 / 요청 / 후보
-- ============================================================================

CREATE TABLE public.routing_policies (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    version varchar(50) NOT NULL UNIQUE,
    survey_weight_map jsonb NOT NULL DEFAULT '{}'::jsonb,
    objective_weight numeric(5,4) NOT NULL,
    preference_weight numeric(5,4) NOT NULL,
    normalization_method varchar(50) NOT NULL DEFAULT 'configurable',
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    rationale text,
    is_active boolean NOT NULL DEFAULT false,
    effective_from timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_routing_policies_objective_weight
        CHECK (objective_weight BETWEEN 0 AND 1),
    CONSTRAINT ck_routing_policies_preference_weight
        CHECK (
            preference_weight BETWEEN 0 AND 1
            AND objective_weight + preference_weight = 1.0000
        )
);

COMMENT ON TABLE public.routing_policies IS
'설문 원점수→가중치, 객관위험/개인화 비율, 정규화 방법을 버전별 관리한다.';

CREATE TABLE public.route_requests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL
        REFERENCES public.users(id) ON DELETE CASCADE,
    navigation_run_id uuid,
    parent_request_id uuid
        REFERENCES public.route_requests(id) ON DELETE SET NULL,
    request_type varchar(20) NOT NULL DEFAULT 'initial',
    reroute_reason varchar(30),

    origin_name varchar(200) NOT NULL,
    origin_address text,
    origin_geom geometry(Point,4326) NOT NULL,
    origin_admin_code varchar(20),
    origin_admin_name varchar(100),
    origin_node_id bigint
        REFERENCES public.road_nodes(id) ON DELETE SET NULL,

    destination_name varchar(200) NOT NULL,
    destination_address text,
    destination_geom geometry(Point,4326) NOT NULL,
    destination_admin_code varchar(20),
    destination_admin_name varchar(100),
    destination_node_id bigint
        REFERENCES public.road_nodes(id) ON DELETE SET NULL,

    max_detour_minutes smallint NOT NULL DEFAULT 10,
    routing_policy_id uuid
        REFERENCES public.routing_policies(id) ON DELETE RESTRICT,
    risk_version varchar(80),
    preference_snapshot jsonb,

    status varchar(20) NOT NULL DEFAULT 'queued',
    failure_code varchar(50),
    failure_message text,
    input_fingerprint char(64) NOT NULL,

    started_at timestamptz,
    completed_at timestamptz,
    duration_ms integer,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_route_requests_type
        CHECK (request_type IN ('initial','reroute')),
    CONSTRAINT ck_route_requests_reroute_reason
        CHECK (
            reroute_reason IS NULL
            OR reroute_reason IN ('off_route','user_request','navigation_error')
        ),
    CONSTRAINT ck_route_requests_detour
        CHECK (max_detour_minutes IN (10,20,30,60)),
    CONSTRAINT ck_route_requests_status
        CHECK (status IN ('queued','processing','success','rejected','failed')),
    CONSTRAINT ck_route_requests_duration
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_route_requests_failure_code
        CHECK (
            failure_code IS NULL
            OR failure_code IN (
                'OUT_OF_SERVICE_AREA',
                'NO_ROUTE',
                'ROUTING_ERROR',
                'MAP_API_ERROR',
                'DATA_NOT_READY',
                'ENGINE_TIMEOUT',
                'INTERNAL_ERROR'
            )
        )
);

COMMENT ON TABLE public.route_requests IS
'최초/재탐색/서비스지역 밖/실패를 포함한 경로 요청 원본. 한 실제 길안내의 재탐색들은 navigation_run_id로 묶는다.';

CREATE TABLE public.route_candidates (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    route_request_id uuid NOT NULL
        REFERENCES public.route_requests(id) ON DELETE CASCADE,
    route_type varchar(20) NOT NULL,
    estimated_seconds integer NOT NULL,
    distance_meters integer NOT NULL,
    detour_minutes numeric(8,2),
    objective_risk_cost numeric(14,6),
    preference_penalty numeric(14,6),
    total_routing_cost numeric(16,6),
    recommendation_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
    feature_summary jsonb,
    geom geometry(LineString,4326) NOT NULL,
    is_selected boolean NOT NULL DEFAULT false,
    selected_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_route_candidates_request_type
        UNIQUE (route_request_id, route_type),
    CONSTRAINT ck_route_candidates_type
        CHECK (route_type IN ('safe','fastest','shortest')),
    CONSTRAINT ck_route_candidates_estimated_seconds
        CHECK (estimated_seconds >= 0),
    CONSTRAINT ck_route_candidates_distance
        CHECK (distance_meters >= 0),
    CONSTRAINT ck_route_candidates_detour
        CHECK (detour_minutes IS NULL OR detour_minutes >= 0),
    CONSTRAINT ck_route_candidates_objective
        CHECK (objective_risk_cost IS NULL OR objective_risk_cost >= 0),
    CONSTRAINT ck_route_candidates_preference
        CHECK (preference_penalty IS NULL OR preference_penalty >= 0),
    CONSTRAINT ck_route_candidates_total
        CHECK (total_routing_cost IS NULL OR total_routing_cost >= 0),
    CONSTRAINT ck_route_candidates_selected_at
        CHECK (is_selected = false OR selected_at IS NOT NULL)
);

COMMENT ON TABLE public.route_candidates IS
'경로 요청별 safe/fastest/shortest 후보. 사용자에게 0~100 안전점수는 노출하지 않고 설명형 이유를 저장한다.';

CREATE TABLE public.route_candidate_links (
    route_candidate_id uuid NOT NULL
        REFERENCES public.route_candidates(id) ON DELETE CASCADE,
    seq integer NOT NULL,
    road_link_id bigint NOT NULL
        REFERENCES public.road_links(id) ON DELETE RESTRICT,
    segment_distance_m numeric(10,2),
    segment_seconds integer,
    segment_cost numeric(12,4),

    PRIMARY KEY (route_candidate_id, seq),

    CONSTRAINT ck_route_candidate_links_seq
        CHECK (seq >= 1),
    CONSTRAINT ck_route_candidate_links_distance
        CHECK (segment_distance_m IS NULL OR segment_distance_m >= 0),
    CONSTRAINT ck_route_candidate_links_seconds
        CHECK (segment_seconds IS NULL OR segment_seconds >= 0),
    CONSTRAINT ck_route_candidate_links_cost
        CHECK (segment_cost IS NULL OR segment_cost >= 0)
);

COMMENT ON TABLE public.route_candidate_links IS
'경로 후보를 구성하는 도로 링크 순서. 실제 턴바이턴 안내 Step은 이 데이터와 road_turns를 이용해 Runtime에서 생성한다.';

-- ============================================================================
-- 6. 공지 / 문의
-- ============================================================================

CREATE TABLE public.notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    content text NOT NULL,
    is_published boolean NOT NULL DEFAULT false,
    published_at timestamptz,
    created_by uuid
        REFERENCES public.admins(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_notices_published_at
        CHECK (is_published = false OR published_at IS NOT NULL)
);

COMMENT ON TABLE public.notices IS
'사용자 공지사항 및 관리자 공지 CRUD 데이터.';

CREATE TABLE public.inquiries (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL
        REFERENCES public.users(id) ON DELETE CASCADE,
    category varchar(50) NOT NULL,
    title varchar(200) NOT NULL,
    content text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'received',
    answer_content text,
    answered_by uuid
        REFERENCES public.admins(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    answered_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_inquiries_status
        CHECK (
            status IN ('received','in_review','answered')
            AND (
                status <> 'answered'
                OR (answer_content IS NOT NULL AND answered_at IS NOT NULL)
            )
        )
);

COMMENT ON TABLE public.inquiries IS
'사용자 문의 원본과 관리자 답변/처리상태.';

COMMIT;