// 최근 50건 안에서 검색·상태 필터·페이지 이동을 제공한다. 상세 정보는 조회된 원본 값을 유지한다.
import {useEffect,useRef,useState} from 'react'
import {Search,RefreshCw,Database,BrainCircuit,X} from 'lucide-react'
import {apiClient} from '../../lib/apiClient.js'
import './operations.css'
const date=value=>value?new Date(value).toLocaleString('ko-KR'):'—'
const fields={release_id:'데이터 식별자',dataset_version:'데이터 버전',feature_version:'도로 특성 버전',eta_version:'예상시간 버전',status:'준비 상태',model_version:'모델 버전',model_type:'모델 유형',is_active:'운영 여부',metrics:'평가 지표',searchId:'검색 ID',createdAt:'검색 일시',modelVersion:'모델 버전',profileVersion:'개인화 버전',sampleOrigin:'기록 출처',candidateCount:'후보 수',recommendedId:'추천 후보 ID',selectedId:'선택 후보 ID',elapsedSeconds:'계산시간(초)',degraded:'제한시간 적용',id:'기록 ID',search_id:'검색 ID',error_code:'오류 코드',duration_ms:'계산시간(ms)',created_at:'기록 일시'}
function Detail({item,onClose}){
    const ref=useRef(null)
    useEffect(()=>{ref.current.showModal()},[])
    return <dialog ref={ref} className="ops-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} aria-labelledby="ops-detail-title"><div className="operations-heading"><div><span className="ops-eyebrow">DETAIL</span><h2 id="ops-detail-title">기록 상세 정보</h2></div><button onClick={onClose} aria-label="상세 닫기"><X size={20}/></button></div><dl>{Object.entries(item).map(([key,value])=><div key={key}><dt>{fields[key]||key}</dt><dd>{value===null?'—':typeof value==='object'?<pre>{JSON.stringify(value,null,2)}</pre>:typeof value==='boolean'?(value?'예':'아니요'):String(value)}</dd></div>)}</dl><button className="ops-primary" onClick={onClose}>확인</button></dialog>
}
export default function OperationsPage({kind}){
    const [data,setData]=useState(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(1),[detail,setDetail]=useState(null)
    const title=kind==='datasets'?'데이터·모델 관리':kind==='failures'?'경로 계산 실패':'경로 검색 기록'
    useEffect(()=>{let live=true;setData(null);setError('');setSearch('');setFilter('all');setPage(1);setDetail(null);apiClient('/admin/operations/'+(kind==='datasets'?'summary':kind)).then(r=>live&&setData(r.data)).catch(e=>live&&setError(e.message));return()=>{live=false}},[kind,attempt])
    const rows=Array.isArray(data)?data.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(kind==='failures'?r.error_code===filter:filter==='selected'?!!r.selectedId:filter==='unselected'?!r.selectedId:r.degraded))):[]
    const pages=Math.max(1,Math.ceil(rows.length/10)),current=Math.min(page,pages)
    return <section className="operations"><div className="operations-heading"><div><span className="ops-eyebrow">{kind==='datasets'?'DATA & MODELS':'ROUTING MONITOR'}</span><h1>{title}</h1><p className="ops-muted">{kind==='datasets'?'검증된 도로 데이터와 추천 모델의 운영 상태를 확인합니다.':'저장된 서비스 기록으로 경로 계산과 이용 흐름을 확인합니다.'}</p></div><button onClick={()=>setAttempt(v=>v+1)}><RefreshCw size={15}/> 새로고침</button></div>
        {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">불러오는 중…</p>}
        {kind==='datasets'&&data&&<><div className="ops-two-columns"><article className="operations-panel"><Database className="ops-feature-icon"/><h2>도로 데이터</h2><strong className="ops-large-number">{data.releases.length}<small> 개 등록</small></strong><p>SQLite/GPKG · 백엔드 적재</p><span className="ops-pill">{data.active?'활성 데이터 연결됨':'활성 데이터 없음'}</span></article><article className="operations-panel"><BrainCircuit className="ops-feature-icon"/><h2>추천 모델</h2><strong className="ops-large-number">{data.models.filter(m=>m.is_active).length}<small> 개 운영</small></strong><p>Logistic · XGBoost 비교</p><span className="ops-pill">합성 학습 자료 · 실제 이용자 성능 미검증</span></article></div>
        <article className="operations-panel"><h2>데이터 등록 내역</h2><p className="ops-muted">동결 원본의 변경과 활성화는 파일 무결성 검증 후 관리 명령으로 진행합니다.</p><div className="operations-scroll"><table><thead><tr><th>데이터</th><th>준비 상태</th><th>운영 상태</th><th>관리</th></tr></thead><tbody>{data.releases.map(r=><tr key={r.release_id}><td><b>서울 도로·시간대별 교통</b><br/><code>{r.release_id}</code></td><td><span className="ops-pill">{r.status==='ready'?'검증 완료':r.status}</span></td><td>{r.release_id===data.active?.release_id?'사용 중':'대기'}</td><td><button onClick={()=>setDetail(r)}>상세 보기</button></td></tr>)}</tbody></table></div></article>
        <article className="operations-panel"><h2>모델 등록 내역</h2><div className="operations-scroll"><table><thead><tr><th>모델</th><th>버전</th><th>운영 상태</th><th>관리</th></tr></thead><tbody>{data.models.map(m=><tr key={m.model_version}><td>{m.model_type==='logistic'?'Logistic Regression':m.model_type==='xgboost'?'XGBoost':'설문 기준'}</td><td><code>{m.model_version}</code></td><td><span className={'ops-pill '+(!m.is_active?'ops-pill-neutral':'')}>{m.is_active?'사용 중':'비활성'}</span></td><td><button onClick={()=>setDetail(m)}>평가·상세</button></td></tr>)}</tbody></table></div></article></>}
        {kind!=='datasets'&&data&&<article className="operations-panel"><div className="ops-toolbar"><label className="ops-search"><Search size={17}/><input type="search" aria-label="기록 검색" placeholder="검색 ID, 모델 또는 오류 코드 검색" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><select aria-label="기록 상태" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="all">전체 상태</option>{kind==='failures'?[...new Set(data.map(r=>r.error_code))].map(code=><option key={code}>{code}</option>):<><option value="selected">선택 완료</option><option value="unselected">미선택</option><option value="degraded">제한시간 적용</option></>}</select><span className="ops-muted">최근 50건 중 {rows.length}건</span></div><div className="operations-scroll"><table><thead><tr>{(kind==='failures'?['일시','검색 ID','오류','계산시간','관리']:['일시','검색 ID','후보','최종 선택','계산시간','관리']).map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.slice((current-1)*10,current*10).map(r=><tr key={r.id||r.searchId}><td>{date(r.created_at||r.createdAt)}</td><td><code>{(r.search_id||r.searchId).slice(0,8)}</code></td>{kind==='failures'?<><td><span className="ops-pill ops-pill-warning">{r.error_code}</span></td><td>{(r.duration_ms/1000).toFixed(2)}초</td></>:<><td>{r.candidateCount}개 {r.degraded&&<span className="ops-pill ops-pill-warning">제한시간</span>}</td><td><span className={'ops-pill '+(!r.selectedId?'ops-pill-neutral':'')}>{r.selectedId?(r.selectedId===r.recommendedId?'추천 경로 선택':'다른 경로 선택'):'미선택'}</span></td><td>{r.elapsedSeconds?.toFixed(2)??'—'}초</td></>}<td><button onClick={()=>setDetail(r)}>상세 보기</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="ops-empty"><Search size={28}/><h3>{search||filter!=='all'?'조건에 맞는 기록이 없습니다':'아직 기록이 없습니다'}</h3><p>검색 조건을 변경하거나 서비스 사용 후 새로고침해주세요.</p>{(search||filter!=='all')&&<button onClick={()=>{setSearch('');setFilter('all');setPage(1)}}>조건 초기화</button>}</div>}<div className="ops-pagination"><button disabled={current===1} onClick={()=>setPage(current-1)}>이전</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>다음</button></div></article>}
        {detail&&<Detail item={detail} onClose={()=>setDetail(null)}/>}
    </section>
}
